### ISSUE TITLE
Handling EVEN

### ISSUE THREAD

**Issue by jolla56** [Jisco/gedcom.json#32]
I'm trying to understand the yaml config but can't get the result I expect. If I have EVEN with no extra text on the line but sub-elements the process turns it into an object with arrays where each type from the various events are collected.
But if I add some random text to each EVEN line I get a proper event array with the different event objects inside.

**Comment by Jisco** [comment]
Sorry, unfortunately I don't understand the problem from your description.
Could you put the 2 scenarios described here as an example? So once the configuration and once the result and then what you actually want as the result?

**Comment by Jisco** [comment]
Hi,
This seems to be already be working via the configuration.

```
  - Tag: EVEN
    CollectAs: Events
    Property: Name
    Properties:
      - Tag: TYPE
        Property: Type
        MergeWithLast: EVEN
      - Tag: PLAC
        Property: Place
        MergeWithLast: EVEN
````

I added this to the default configuration yaml.
