### ISSUE TITLE
Bug on parsing PLAC tags

### ISSUE THREAD

**Issue by joaogsousa** [Jisco/gedcom.json#44]
**Describe the bug**
There is a bug around parsing PLAC tags in the gedcom. More specifically, PLAC tags that contain a MAP tag, and LATI and LONG tags within it.

**To Reproduce**
To reproduce try parsing the attached gedcom.

[Douglas family tree(2)_2024-12-11 (1) (1).zip](https://github.com/user-attachments/files/18477584/Douglas.family.tree.2._2024-12-11.1.1.zip)

You should get an error as so:
ERROR: Cannot create property 'Map' on string 'Fylingdales, Yorkshire, England'

**Expected behavior**
I would expect the JSON to be correctly generated with all the info contained in the PLAC tags

**Screenshots**

![Image](https://github.com/user-attachments/assets/4dba00ed-f7c6-42c4-b3a8-7e98d5753a81)
![Image](https://github.com/user-attachments/assets/cab3bcc0-e78b-4933-8843-9515351b1cab)

**Comment by Jisco** [comment]
Hi,
Unfortunately the error text is a bit misleading. I have to improve it 😅.

Anyway, the problem is that PLAC appears multiple times under some other tags. In your case this applies to BAPM, BIRT, MARR and RESI.

I still understand MARR and RESI. But I'm really unsure about BIRT ^^

Your problem can be solved if you adapt your config yaml and allow several entries there and then let combine them.

Example BAPM:

Replace:
```yaml
  - Tag: BAPM
    Property: Baptism
```

with:
```yaml
  - Tag: BAPM
    Property: Baptism
    CollectAs: Baptisms
    CollectAsArray: true
    Properties:
      - Tag: PLAC
        Property: Place
        MergeWithLast: BAPM
      - Tag: DATE
        Property: Date
        Type: Date
        MergeWithLast: BAPM
```

Same for BIRT, MARR and RESI.

I'll think about what should actually be standard for the future.
